name: Deploy to OSS

on:
  push:
    branches:
      - master # 替换为你的默认分支

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 18

      - name: Build VitePress
        run: |
          npm install
          npm run docs:build
          echo 'element.hackslog.com' > docs/.vitepress/dist/CNAME
          mv docs/.vitepress/dist ./

      - name: Upload to OSS
        uses: YangHanlin/oss-deployment-action@v1
        with:
          oss-endpoint: ${{ ALIYUN_OSS_REGION }}.aliyuncs.com
          access-key-id: ${{ secrets.ALIYUN_OSS_ACCESS_KEY_ID }}
          access-key-secret: ${{ secrets.ALIYUN_OSS_ACCESS_KEY_SECRET }}
          oss-path: oss://${{ ALIYUN_OSS_BUCKET }}/
